name: flutter_translatable
description: A sample command-line application.
version: 0.0.1-1
repository: https://github.com/s7np8k/flutter_translatable.git

environment:
  sdk: ^3.0.0

dependencies:
  glob: ^2.1.2
  args: ^2.4.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
