name: flutter_translatable
description: A sample command-line application.
version: 0.0.1-2
repository: https://github.com/s7np8k/flutter_translatable.git

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
